import type { Metadata } from "next";
import "./globals.css";
import { FloatingNav } from "@/components/ui/Floating-Navbar";
import { navigationItems } from "@/data";


export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white antialiased">
        <FloatingNav navItems={navigationItems}/>
        {children}
      </body>
    </html>
  );
}
